model_params:
  name: 'VampVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset_name: 'CelebA'
  # data_path: "/data/users/gkoren2/datasets/celeba/"   # gpu15
  data_path: "/home/guy/sd1tb/datasets/CelebA/"   # guyx
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "VampVAE"
  manual_seed: 1265
